### ISSUE TITLE
Server crash when accidentaly put a ` character before exit name

### ISSUE THREAD

**Issue by OliverLSanz** [OliverLSanz/sandbox_mud#12]
This is the error log
```
mud_1           | Traceback (most recent call last):
mud_1           |   File "./server.py", line 106, in <module>
mud_1           |     sessions[sender_client].process_message(message)
mud_1           |   File "./server.py", line 24, in process_message
mud_1           |     self.current_verb.process(message)
mud_1           |   File "/usr/src/app/verbs/go.py", line 17, in process
mud_1           |     elif [exit in room_exit for room_exit in self.session.user.room.exits.keys()].count(True) > 1:
mud_1           |   File "/usr/src/app/verbs/go.py", line 17, in <listcomp>
mud_1           |     elif [exit in room_exit for room_exit in self.session.user.room.exits.keys()].count(True) > 1:
mud_1           | TypeError: 'in <string>' requires string as left operand, not Quitter
```

**Comment by OliverLSanz** [comment]
Can't replicate, seems to be fixed now.
