### ISSUE TITLE
Crash when client sends non utf-8 data

### ISSUE THREAD

**Issue by OliverLSanz** [OliverLSanz/sandbox_mud#25]
Probably it was latin-1. Traceback here:
```
mud_1           | Traceback (most recent call last):
mud_1           |   File "./server.py", line 106, in <module>
mud_1           |     sessions[sender_client].process_message(message)
mud_1           |   File "./server.py", line 24, in process_message
mud_1           |     self.current_verb.process(message)
mud_1           |   File "/usr/src/app/verbs/go.py", line 17, in process
mud_1           |     elif [exit in room_exit for room_exit in self.session.user.room.exits.keys()].count(True) > 1:
mud_1           |   File "/usr/src/app/verbs/go.py", line 17, in <listcomp>
mud_1           |     elif [exit in room_exit for room_exit in self.session.user.room.exits.keys()].count(True) > 1:
mud_1           | TypeError: 'in <string>' requires string as left operand, not Quitter
mud_1           | Traceback (most recent call last):
mud_1           |   File "./server.py", line 93, in <module>
mud_1           |     server.update()
mud_1           |   File "/usr/local/lib/python3.8/site-packages/telnetserver/telnetserver.py", line 123, in update
mud_1           |     self._check_for_messages()
mud_1           |   File "/usr/local/lib/python3.8/site-packages/telnetserver/telnetserver.py", line 288, in _check_for_messages
mud_1           |     data = cl.socket.recv(4096).decode(self.encoding)
mud_1           | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 5: invalid continuation byte
```

**Comment by OliverLSanz** [comment]
This was resolved by b2cb360.
